Praktikum 1


Backpropagation adalah sebuah algoritma untuk melatih jaringan saraf tiruan dengan cara mengoreksi kesalahan. Algoritma ini bekerja dengan cara menghitung selisih antara keluaran yang dihasilkan jaringan dan keluaran yang seharusnya (kesalahan), lalu memperbarui bobot dan bias jaringan secara berulang dari keluaran ke masukan untuk meminimalkan kesalahan tersebut. Cara kerja backpropagation

- Perambatan maju (forward pass): Data masukan diproses melalui jaringan dari lapisan masukan ke lapisan keluaran untuk menghasilkan prediksi awal.

- Hitung kesalahan: Selisih antara keluaran prediksi dan keluaran target dihitung menggunakan fungsi kerugian.

- Perambatan mundur (backward pass): Kesalahan disebarkan kembali ke belakang melalui jaringan dari lapisan keluaran ke lapisan masukan untuk menghitung gradien atau turunan parsial dari fungsi kerugian terhadap bobot dan bias.

- Perbarui bobot: Bobot dan bias disesuaikan menggunakan algoritma penurunan gradien untuk mengurangi kesalahan pada iterasi berikutnya. 

Langkah:

1. Buat dataset sederhana (XOR).
2. Inisialisasi bobot dan bias.
3. Implementasikan forward pass.
4. Hitung error dan lakukan backpropagation.
5. Update bobot menggunakan gradient descent.

In [1]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 2
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.2871315980752797
Epoch 1000, Loss: 0.24845915018376988
Epoch 2000, Loss: 0.23803833898065468
Epoch 3000, Loss: 0.20197139272498665
Epoch 4000, Loss: 0.1651626767582322
Epoch 5000, Loss: 0.05998133824643194
Epoch 6000, Loss: 0.024097272895750622
Epoch 7000, Loss: 0.013884889221315717
Epoch 8000, Loss: 0.009486898336613925
Epoch 9000, Loss: 0.007114449003771177
Prediksi:
[[0.07290717]
 [0.91788063]
 [0.92059885]
 [0.06519047]]


In [2]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Hitung error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update bobot
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"Epoch {epoch}, Loss: {loss}")

# Output akhir
print("Prediksi:")
print(a2)

Epoch 0, Loss: 0.2627608632517608
Epoch 1000, Loss: 0.1801062670511817
Epoch 2000, Loss: 0.042708546595260966
Epoch 3000, Loss: 0.013039274750646116
Epoch 4000, Loss: 0.006982045411409443
Epoch 5000, Loss: 0.0046429730291877086
Epoch 6000, Loss: 0.003439366018431013
Epoch 7000, Loss: 0.0027154566118487828
Epoch 8000, Loss: 0.0022355146580245256
Epoch 9000, Loss: 0.0018954587440655666
Prediksi:
[[0.02698094]
 [0.95956056]
 [0.95843075]
 [0.0498004 ]]


Tugas 1:



Ubah jumlah neuron hidden layer menjadi 3.

In [3]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3   
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Fungsi aktivasi
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Error
    error = y - a2

    # Backpropagation
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update weight
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"[Hidden = 3] Epoch {epoch}, Loss: {loss}")

print("\nPrediksi (Hidden 3):")
print(a2)


[Hidden = 3] Epoch 0, Loss: 0.26812281148055644
[Hidden = 3] Epoch 1000, Loss: 0.2476699890495169
[Hidden = 3] Epoch 2000, Loss: 0.23157278638181727
[Hidden = 3] Epoch 3000, Loss: 0.15516331582714915
[Hidden = 3] Epoch 4000, Loss: 0.03219767728604328
[Hidden = 3] Epoch 5000, Loss: 0.012098953958886518
[Hidden = 3] Epoch 6000, Loss: 0.006956921011184971
[Hidden = 3] Epoch 7000, Loss: 0.004774727770534475
[Hidden = 3] Epoch 8000, Loss: 0.0035977736857096864
[Hidden = 3] Epoch 9000, Loss: 0.0028701713630250175

Prediksi (Hidden 3):
[[0.03267232]
 [0.95211886]
 [0.94647064]
 [0.05738209]]


Bandingkan hasil loss dengan konfigurasi awal.



In [4]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter awal
input_size = 2
hidden_size = 2 
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for epoch in range(10000):
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    error = y - a2

    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * sigmoid_derivative(a1)
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"[Hidden = 2] Epoch {epoch}, Loss: {loss}")

print("\nPrediksi (Hidden 2):")
print(a2)


[Hidden = 2] Epoch 0, Loss: 0.25715936418548585
[Hidden = 2] Epoch 1000, Loss: 0.22402717489958923
[Hidden = 2] Epoch 2000, Loss: 0.16375267966065188
[Hidden = 2] Epoch 3000, Loss: 0.1417083868807285
[Hidden = 2] Epoch 4000, Loss: 0.1348224189306883
[Hidden = 2] Epoch 5000, Loss: 0.1317897026337282
[Hidden = 2] Epoch 6000, Loss: 0.13013341363571373
[Hidden = 2] Epoch 7000, Loss: 0.12910335362256972
[Hidden = 2] Epoch 8000, Loss: 0.12840576160098294
[Hidden = 2] Epoch 9000, Loss: 0.12790420670029334

Prediksi (Hidden 2):
[[0.04621345]
 [0.95682775]
 [0.4964345 ]
 [0.50252646]]


Tambahkan fungsi aktivasi ReLU dan bandingkan hasil.



In [5]:
import numpy as np

# Dataset XOR
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[0]])

# Parameter
input_size = 2
hidden_size = 3
output_size = 1
lr = 0.1

# Inisialisasi bobot
W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))
W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# ReLU
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

# Sigmoid untuk output layer
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training ReLU
for epoch in range(10000):
    # Forward
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)            # ReLU di hidden
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)

    # Error
    error = y - a2

    # Backward
    d_a2 = error * sigmoid_derivative(a2)
    d_W2 = np.dot(a1.T, d_a2)
    d_b2 = np.sum(d_a2, axis=0, keepdims=True)

    d_a1 = np.dot(d_a2, W2.T) * relu_derivative(z1)  # backprop pakai ReLU derivative
    d_W1 = np.dot(X.T, d_a1)
    d_b1 = np.sum(d_a1, axis=0, keepdims=True)

    # Update weight
    W1 += lr * d_W1
    b1 += lr * d_b1
    W2 += lr * d_W2
    b2 += lr * d_b2

    if epoch % 1000 == 0:
        loss = np.mean(np.square(error))
        print(f"[ReLU Hidden=3] Epoch {epoch}, Loss: {loss}")

print("\nPrediksi (ReLU Hidden 3):")
print(a2)


[ReLU Hidden=3] Epoch 0, Loss: 0.2542200561521639
[ReLU Hidden=3] Epoch 1000, Loss: 0.009876166283346335
[ReLU Hidden=3] Epoch 2000, Loss: 0.0029731507874242984
[ReLU Hidden=3] Epoch 3000, Loss: 0.001632296559539261
[ReLU Hidden=3] Epoch 4000, Loss: 0.0010997405611571438
[ReLU Hidden=3] Epoch 5000, Loss: 0.0008191891369290097
[ReLU Hidden=3] Epoch 6000, Loss: 0.000648957207138665
[ReLU Hidden=3] Epoch 7000, Loss: 0.0005348315883157621
[ReLU Hidden=3] Epoch 8000, Loss: 0.00045381642693425515
[ReLU Hidden=3] Epoch 9000, Loss: 0.00039309453222324483

Prediksi (ReLU Hidden 3):
[[0.02949042]
 [0.98618376]
 [0.9861839 ]
 [0.01157227]]
